-- Reverso de la carga DATA-PRUEBA.xls para PostgreSQL.
-- Úselo solamente para deshacer la carga inicial antes de crear información operativa adicional.
-- La transacción se revierte íntegramente si existen dependencias posteriores que impidan borrar un registro.
-- psql -v instance_country_id='UUID-DE-LA-INSTANCIA' -f revert_import_data_prueba.sql

\if :{?instance_country_id}
\else
\echo 'Debe indicar -v instance_country_id=UUID-DE-LA-INSTANCIA'
\quit
\endif

BEGIN;
SELECT set_config('app.import.instance_country_id', :'instance_country_id', true);

CREATE TEMP TABLE import_data_prueba_reverse (
  client_code text, service_code text, point_code text, post_code2 text,
  base_code text, source_signature text, post_sequence integer
) ON COMMIT DROP;

INSERT INTO import_data_prueba_reverse VALUES
('CLI-CM-EC-61', 'SER-CM-EC-4806', 'PTO-CM-EC-724', 'PUE-CM-EC-26943', 'EETE', 'ESMERALDAS|ESMERALDAS|TELCONETSA|ESMERALDAS', 1),
('CLI-CM-EC-61', 'SER-CM-EC-4806', 'PTO-CM-EC-724', 'PUE-CM-EC-10252', 'EETE', 'ESMERALDAS|ESMERALDAS|TELCONETSA|ESMERALDAS', 2),
('CLI-CM-EC-61', 'SER-CM-EC-2217', 'PTO-CM-EC-1167', 'PUE-CM-EC-16813', 'LBTT', 'LOSRIOS|BABAHOYO|TELCONETSA|TELCONETBABAHOYO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2217', 'PTO-CM-EC-1167', 'PUE-CM-EC-20157', 'LBTT', 'LOSRIOS|BABAHOYO|TELCONETSA|TELCONETBABAHOYO', 2),
('CLI-CM-EC-61', 'SER-CM-EC-3155', 'PTO-CM-EC-1603', 'PUE-CM-EC-21243', 'TATA', 'TUNGURAHUA|AMBATO|TELCONETSA|AMBATO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3155', 'PTO-CM-EC-1603', 'PUE-CM-EC-21242', 'TATA', 'TUNGURAHUA|AMBATO|TELCONETSA|AMBATO', 2),
('CLI-CM-EC-61', 'SER-CM-EC-2282', 'PTO-CM-EC-125', 'PUE-CM-EC-17192', 'SSTS', 'SANTAELENA|SALINAS|TELCONETSA|SUCURSALSALINAS', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2282', 'PTO-CM-EC-125', 'PUE-CM-EC-1265', 'SSTS', 'SANTAELENA|SALINAS|TELCONETSA|SUCURSALSALINAS', 2),
('CLI-CM-EC-61', 'SER-CM-EC-4048', 'PTO-CM-EC-1937', 'PUE-CM-EC-24720', 'PQTG', 'PICHINCHA|QUITO|TELCONETSA|GOSSEAL', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3416', 'PTO-CM-EC-1462', 'PUE-CM-EC-22163', 'PQTT', 'PICHINCHA|QUITO|TELCONETSA|TELCONETGUAMANI', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3416', 'PTO-CM-EC-1462', 'PUE-CM-EC-19764', 'PQTT', 'PICHINCHA|QUITO|TELCONETSA|TELCONETGUAMANI', 2),
('CLI-CM-EC-61', 'SER-CM-EC-3416', 'PTO-CM-EC-1462', 'PUE-CM-EC-19671', 'PQTT', 'PICHINCHA|QUITO|TELCONETSA|TELCONETGUAMANI', 3),
('CLI-CM-EC-61', 'SER-CM-EC-207', 'PTO-CM-EC-112', 'PUE-CM-EC-1256', 'PQTB', 'PICHINCHA|QUITO|TELCONETSA|BODEGAUIO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-207', 'PTO-CM-EC-112', 'PUE-CM-EC-1257', 'PQTB', 'PICHINCHA|QUITO|TELCONETSA|BODEGAUIO', 2),
('CLI-CM-EC-61', 'SER-CM-EC-4236', 'PTO-CM-EC-1282', 'PUE-CM-EC-25128', 'SSTA', 'SANTAELENA|SANTAELENA|TELCONETSA|ANCONCITO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-4236', 'PTO-CM-EC-1282', 'PUE-CM-EC-17908', 'SSTA', 'SANTAELENA|SANTAELENA|TELCONETSA|ANCONCITO', 2),
('CLI-CM-EC-61', 'SER-CM-EC-209', 'PTO-CM-EC-113', 'PUE-CM-EC-1259', 'PQTA', 'PICHINCHA|QUITO|TELCONETSA|ACEITUNOS', 1),
('CLI-CM-EC-61', 'SER-CM-EC-209', 'PTO-CM-EC-113', 'PUE-CM-EC-20565', 'PQTA', 'PICHINCHA|QUITO|TELCONETSA|ACEITUNOS', 2),
('CLI-CM-EC-61', 'SER-CM-EC-213', 'PTO-CM-EC-122', 'PUE-CM-EC-1264', 'ACTS', 'AZUAY|CUENCA|TELCONETSA|SUCURSALCUENCA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-215', 'PTO-CM-EC-111', 'PUE-CM-EC-1266', 'PQTM', 'PICHINCHA|QUITO|TELCONETSA|MARIANADEJESUS', 1),
('CLI-CM-EC-61', 'SER-CM-EC-215', 'PTO-CM-EC-111', 'PUE-CM-EC-1267', 'PQTM', 'PICHINCHA|QUITO|TELCONETSA|MARIANADEJESUS', 2),
('CLI-CM-EC-61', 'SER-CM-EC-215', 'PTO-CM-EC-111', 'PUE-CM-EC-1269', 'PQTM', 'PICHINCHA|QUITO|TELCONETSA|MARIANADEJESUS', 3),
('CLI-CM-EC-61', 'SER-CM-EC-579', 'PTO-CM-EC-419', 'PUE-CM-EC-6584', 'EMTM', 'ELORO|MACHALA|TELCONETSA|MACHALA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3787', 'PTO-CM-EC-1466', 'PUE-CM-EC-23802', 'EMTM', 'ELORO|MACHALA|TELCONETSA|MACHALA', 2),
('CLI-CM-EC-61', 'SER-CM-EC-3770', 'PTO-CM-EC-1868', 'PUE-CM-EC-23776', 'PQTC', 'PICHINCHA|QUITO|TELCONETSA|CASADEGERENCIA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-4044', 'PTO-CM-EC-1936', 'PUE-CM-EC-24714', 'PQTT', 'PICHINCHA|QUITO|TELCONETSA|TABIAZO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3285', 'PTO-CM-EC-819', 'PUE-CM-EC-21689', 'ACTC', 'AZUAY|CUENCA|TELCONETSA|CUENCA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3285', 'PTO-CM-EC-819', 'PUE-CM-EC-13512', 'ACTC', 'AZUAY|CUENCA|TELCONETSA|CUENCA', 2),
('CLI-CM-EC-61', 'SER-CM-EC-2946', 'PTO-CM-EC-454', 'PUE-CM-EC-20369', 'LQTB', 'LOSRIOS|QUEVEDO|TELCONETSA|BODEGAQUEVEDO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2946', 'PTO-CM-EC-454', 'PUE-CM-EC-7212', 'LQTB', 'LOSRIOS|QUEVEDO|TELCONETSA|BODEGAQUEVEDO', 2),
('CLI-CM-EC-61', 'SER-CM-EC-1462', 'PTO-CM-EC-719', 'PUE-CM-EC-10234', 'SSTS', 'SANTODOMINGODELOSTSACHILAS|SANTODOMINGO|TELCONETSA|SANTODOMINGO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-1836', 'PTO-CM-EC-923', 'PUE-CM-EC-13313', 'CRTR', 'CHIMBORAZO|RIOBAMBA|TELCONETSA|RIOBAMBA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-1844', 'PTO-CM-EC-925', 'PUE-CM-EC-13322', 'MPTP', 'MANABI|PORTOVIEJO|TELCONETSA|PORTOVIEJO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-1876', 'PTO-CM-EC-943', 'PUE-CM-EC-13377', 'LLTT', 'LOJA|LOJA|TELCONETSA|TELCONETEDIFICIOLOJA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2861', 'PTO-CM-EC-448', 'PUE-CM-EC-20007', 'PQTM', 'PICHINCHA|QUITO|TELCONETSA|METROPARQUEO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2861', 'PTO-CM-EC-448', 'PUE-CM-EC-7196', 'PQTM', 'PICHINCHA|QUITO|TELCONETSA|METROPARQUEO', 2),
('CLI-CM-EC-61', 'SER-CM-EC-6003', 'PTO-CM-EC-2538', 'PUE-CM-EC-30132', 'OFTE', 'ORELLANA|FRANCISCODEORELLANACOCA|TELCONETSA|ELCOCA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2447', 'PTO-CM-EC-632', 'PUE-CM-EC-17972', 'IITI', 'IMBABURA|IBARRA|TELCONETSA|IBARRA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2447', 'PTO-CM-EC-632', 'PUE-CM-EC-9217', 'IITI', 'IMBABURA|IBARRA|TELCONETSA|IBARRA', 2),
('CLI-CM-EC-61', 'SER-CM-EC-5277', 'PTO-CM-EC-2392', 'PUE-CM-EC-28457', 'SSTC', 'SANTAELENA|SANTAELENA|TELCONETSA|CASAGERENCIAAYANGUE', 1),
('CLI-CM-EC-61', 'SER-CM-EC-210', 'PTO-CM-EC-115', 'PUE-CM-EC-1260', 'PQTA', 'PICHINCHA|QUITO|TELCONETSA|ARMENIA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-212', 'PTO-CM-EC-121', 'PUE-CM-EC-1263', 'MMTS', 'MANABI|MANTA|TELCONETSA|SUCURSALMANTA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-1375', 'PTO-CM-EC-692', 'PUE-CM-EC-9897', 'MMTT', 'MANABI|MANTA|TELCONETSA|TELCONETMANTA', 1),
('CLI-CM-EC-61', 'SER-CM-EC-1978', 'PTO-CM-EC-866', 'PUE-CM-EC-13714', 'MMTT', 'MANABI|MANTA|TELCONETSA|TELCONETTECNICASUCURSALMANTAMONITOREO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-3661', 'PTO-CM-EC-1807', 'PUE-CM-EC-23057', 'PQTL', 'PICHINCHA|QUITO|TELCONETSA|LAGOAGRIO', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2044', 'PTO-CM-EC-1041', 'PUE-CM-EC-14387', 'LLTT', 'LOJA|LOJA|TELCONETSA|TELCONETLOJAGARAJE', 1),
('CLI-CM-EC-61', 'SER-CM-EC-2157', 'PTO-CM-EC-1131', 'PUE-CM-EC-16337', 'PQTN', 'PICHINCHA|QUITO|TELCONETSA|NODOBASESUR', 1),
('CLI-CM-EC-36', 'SER-CM-EC-5680', 'PTO-CM-EC-2490', 'PUE-CM-EC-29292', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NETLIFEVALLEDELOSCHILLOS', 1),
('CLI-CM-EC-36', 'SER-CM-EC-5680', 'PTO-CM-EC-2490', 'PUE-CM-EC-29291', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NETLIFEVALLEDELOSCHILLOS', 2),
('CLI-CM-EC-36', 'SER-CM-EC-4796', 'PTO-CM-EC-2223', 'PUE-CM-EC-26916', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NETLIFEEDIFICIOVIVANCONUNEZDEVELA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1361', 'PTO-CM-EC-680', 'PUE-CM-EC-9810', 'CRMN', 'CHIMBORAZO|RIOBAMBA|MEGADATOSSA|NETLIFERIOBAMBA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1680', 'PTO-CM-EC-813', 'PUE-CM-EC-12306', 'TAMN', 'TUNGURAHUA|AMBATO|MEGADATOSSA|NETLIFEAMBATO', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1680', 'PTO-CM-EC-813', 'PUE-CM-EC-30170', 'TAMN', 'TUNGURAHUA|AMBATO|MEGADATOSSA|NETLIFEAMBATO', 2),
('CLI-CM-EC-36', 'SER-CM-EC-3377', 'PTO-CM-EC-736', 'PUE-CM-EC-22080', 'SSMN', 'SANTODOMINGODELOSTSACHILAS|SANTODOMINGO|MEGADATOSSA|NETLIFESANTODOMINGO', 1),
('CLI-CM-EC-36', 'SER-CM-EC-3377', 'PTO-CM-EC-736', 'PUE-CM-EC-29733', 'SSMN', 'SANTODOMINGODELOSTSACHILAS|SANTODOMINGO|MEGADATOSSA|NETLIFESANTODOMINGO', 2),
('CLI-CM-EC-36', 'SER-CM-EC-1492', 'PTO-CM-EC-727', 'PUE-CM-EC-10378', 'EMMN', 'ELORO|MACHALA|MEGADATOSSA|NETLIFEMACHALA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1502', 'PTO-CM-EC-735', 'PUE-CM-EC-10393', 'MMMN', 'MANABI|MANTA|MEGADATOSSA|NETLIFEMANTA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1955', 'PTO-CM-EC-993', 'PUE-CM-EC-13655', 'LQMQ', 'LOSRIOS|QUEVEDO|MEGADATOSSA|QUEVEDOLAQUADRA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-2081', 'PTO-CM-EC-1069', 'PUE-CM-EC-14741', 'PQMV', 'PICHINCHA|QUITO|MEGADATOSSA|VILLAFLORA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-2081', 'PTO-CM-EC-1069', 'PUE-CM-EC-14744', 'PQMV', 'PICHINCHA|QUITO|MEGADATOSSA|VILLAFLORA', 2),
('CLI-CM-EC-36', 'SER-CM-EC-2614', 'PTO-CM-EC-1406', 'PUE-CM-EC-18943', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NETLIFEGRANAKISOLANDA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-2614', 'PTO-CM-EC-1406', 'PUE-CM-EC-22947', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NETLIFEGRANAKISOLANDA', 2),
('CLI-CM-EC-36', 'SER-CM-EC-2845', 'PTO-CM-EC-1495', 'PUE-CM-EC-19943', 'IIMN', 'IMBABURA|IBARRA|MEGADATOSSA|NETLIFEIBARRA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-2845', 'PTO-CM-EC-1495', 'PUE-CM-EC-19944', 'IIMN', 'IMBABURA|IBARRA|MEGADATOSSA|NETLIFEIBARRA', 2),
('CLI-CM-EC-36', 'SER-CM-EC-3724', 'PTO-CM-EC-1853', 'PUE-CM-EC-23687', 'SSMN', 'SANTAELENA|SALINAS|MEGADATOSSA|NELTIFESALINAS', 1),
('CLI-CM-EC-36', 'SER-CM-EC-552', 'PTO-CM-EC-383', 'PUE-CM-EC-6484', 'ACMN', 'AZUAY|CUENCA|MEGADATOSSA|NETLIFECUENCA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1321', 'PTO-CM-EC-659', 'PUE-CM-EC-9381', 'LQMN', 'LOSRIOS|QUEVEDO|MEGADATOSSA|NETLIFEQUEVEDO', 1),
('CLI-CM-EC-36', 'SER-CM-EC-1321', 'PTO-CM-EC-659', 'PUE-CM-EC-9382', 'LQMN', 'LOSRIOS|QUEVEDO|MEGADATOSSA|NETLIFEQUEVEDO', 2),
('CLI-CM-EC-36', 'SER-CM-EC-2084', 'PTO-CM-EC-1070', 'PUE-CM-EC-14745', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NELTLIFEBODEGA', 1),
('CLI-CM-EC-36', 'SER-CM-EC-2605', 'PTO-CM-EC-1401', 'PUE-CM-EC-18909', 'MPMN', 'MANABI|PORTOVIEJO|MEGADATOSSA|NETLIFEPORTOVIEJO', 1),
('CLI-CM-EC-36', 'SER-CM-EC-3045', 'PTO-CM-EC-1566', 'PUE-CM-EC-20884', 'PQMN', 'PICHINCHA|QUITO|MEGADATOSSA|NETLIFETORREDELPUENTE', 1);

DO $$
DECLARE
  v_instance uuid := current_setting('app.import.instance_country_id')::uuid;
BEGIN
  -- Se eliminan primero las dependencias propias de cada puesto de esta carga.
  DELETE FROM post_shift_template t
  USING post p, import_data_prueba_reverse i
  WHERE t.post_id=p.id AND p.code2=i.post_code2 AND p.instance_country_id=v_instance;

  DELETE FROM post_planning_cycle_snapshot c
  USING post p, import_data_prueba_reverse i
  WHERE c.post_id=p.id AND p.code2=i.post_code2 AND p.instance_country_id=v_instance;

  DELETE FROM post p
  USING import_data_prueba_reverse i
  WHERE p.code2=i.post_code2 AND p.instance_country_id=v_instance;

  -- Solo se borra la asignación si no fue ampliada posteriormente por nuevos puestos.
  DELETE FROM post_code_allocation a
  USING (
    SELECT base_code, source_signature, max(post_sequence) AS last_sequence
    FROM import_data_prueba_reverse GROUP BY base_code, source_signature
  ) i
  WHERE a.instance_country_id=v_instance
    AND a.base_code=i.base_code
    AND a.source_signature=i.source_signature
    AND a.last_sequence=i.last_sequence;

  -- Un punto, servicio o cliente se elimina únicamente si ya no tiene hijos.
  DELETE FROM point p
  USING (SELECT DISTINCT point_code FROM import_data_prueba_reverse) i
  WHERE p.instance_country_id=v_instance AND p.code=i.point_code
    AND NOT EXISTS (SELECT 1 FROM post po WHERE po.point_id=p.id);

  DELETE FROM service s
  USING (SELECT DISTINCT service_code FROM import_data_prueba_reverse) i
  WHERE s.instance_country_id=v_instance AND s.code=i.service_code
    AND NOT EXISTS (SELECT 1 FROM point p WHERE p.service_id=s.id);

  DELETE FROM client c
  USING (SELECT DISTINCT client_code FROM import_data_prueba_reverse) i
  WHERE c.instance_country_id=v_instance AND c.code=i.client_code
    AND NOT EXISTS (SELECT 1 FROM service s WHERE s.client_id=c.id);
END $$;

COMMIT;
