import {useEffect,useMemo,useRef,useState} from 'react';
import type {MouseEvent as ReactMouseEvent} from 'react';
import {
  AlertTriangle,ArrowLeft,BadgeCheck,Camera,Check,ChevronRight,Clock,FileImage,History,Image as ImageIcon,Info,Map as MapIcon,MapPin,Navigation,Plus,RefreshCcw,Route,Save,Search,ShieldCheck,Smartphone,Trash2,Upload,X
} from 'lucide-react';
import {api} from '../api';

type PointPost={postId:string;postCode:string;postName:string;tier:string;state:string};
type PointContext={pointId:string;pointName:string;pointCode:string;clientName:string;companyName:string;serviceName:string;serviceCode:string;posts:PointPost[]};
type ProtocolStatus='BORRADOR'|'VIGENTE'|'NO_VIGENTE';
type RuleType='INSPECCION_VISUAL'|'FOTOGRAFIA'|'CONFIRMACION'|'LECTURA';
type Rule={id:string;checkpointId:string;sortOrder:number;ruleType:RuleType;required:boolean;evidenceRequired:boolean};
type Checkpoint={id:string;patrolId:string;sortOrder:number;code:string;name:string;description:string;originMode:'ATS'|'FIELD'|'MIXED';atsPackageId?:string|null;atsX?:number|null;atsY?:number|null;latitude?:number|null;longitude?:number|null;gpsAccuracyM?:number|null;locationCapturedAt?:string|null;locationCapturedBy?:string|null;controlType:RuleType;requiresEvidence:boolean;hasStandardImage:boolean;standardImageOriginalName?:string|null;standardImageVersion:number;standardImageNotes:string;visintEnabled:boolean;rules:Rule[]};
type Patrol={id:string;protocolId:string;code:string;name:string;description:string;structureType:'CLOSED'|'OPEN';scheduleType:'PROGRAMMED'|'UNPROGRAMMED';sequenceType:'STRICT'|'FLEXIBLE'|null;windowStart?:string|null;windowEnd?:string|null;repetitions:number;versionNo:number;updatedBy:string;checkpoints:Checkpoint[]};
type Protocol={id:string;seriesId:string;basedOnProtocolId?:string|null;postId:string;code:string;name:string;description:string;status:ProtocolStatus;versionNo:number;lastPublishedAt?:string|null;updatedBy:string;patrols:Patrol[]};
type AtsMeta={id:string;revisionNo:number;planOriginalFilename?:string|null;planWidthPx?:number|null;planHeightPx?:number|null};
type Tab='DEFINICION'|'PROGRAMACION'|'HITOS'|'REGLAS'|'EVIDENCIAS'|'VERSIONADO';

const RULE_LABEL:Record<RuleType,string>={INSPECCION_VISUAL:'Inspección visual',FOTOGRAFIA:'Fotografía',CONFIRMACION:'Confirmación',LECTURA:'Lectura'};
function statusLabel(status:ProtocolStatus){return status==='BORRADOR'?'Borrador':status==='VIGENTE'?'Vigente':'No vigente'}
function structureLabel(v:Patrol['structureType']){return v==='CLOSED'?'Cerrada':'Abierta'}
function scheduleLabel(v:Patrol['scheduleType']){return v==='PROGRAMMED'?'Programada':'No programada'}
function errorText(e:unknown){return e instanceof Error?e.message:String(e)}
function clonePatrol(p:Patrol):Patrol{return {...p,checkpoints:p.checkpoints.map(c=>({...c,rules:c.rules.map(r=>({...r}))}))}}

export default function PatrolConfig({point,onBack}:{point:PointContext;onBack:()=>void}){
  const [protocols,setProtocols]=useState<Protocol[]>([]);
  const [selectedPostId,setSelectedPostId]=useState(point.posts[0]?.postId??'');
  const [selectedProtocolId,setSelectedProtocolId]=useState('');
  const [selectedPatrolId,setSelectedPatrolId]=useState('');
  const [selectedCheckpointId,setSelectedCheckpointId]=useState('');
  const [patrolDraft,setPatrolDraft]=useState<Patrol|null>(null);
  const [protocolName,setProtocolName]=useState('');
  const [protocolDescription,setProtocolDescription]=useState('');
  const [tab,setTab]=useState<Tab>('HITOS');
  const [query,setQuery]=useState('');
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [history,setHistory]=useState<Protocol[]|null>(null);
  const [ats,setAts]=useState<AtsMeta|null>(null);
  const [planUrl,setPlanUrl]=useState('');
  const planUrlRef=useRef('');
  const [placementMode,setPlacementMode]=useState<'NEW_ATS'|'LINK_SELECTED'|null>(null);
  const [standardUrl,setStandardUrl]=useState('');
  const standardUrlRef=useRef('');
  const photoInput=useRef<HTMLInputElement>(null);

  const revokePlan=()=>{if(planUrlRef.current)URL.revokeObjectURL(planUrlRef.current);planUrlRef.current='';setPlanUrl('')};
  const revokeStandard=()=>{if(standardUrlRef.current)URL.revokeObjectURL(standardUrlRef.current);standardUrlRef.current='';setStandardUrl('')};
  const setPlan=(url:string)=>{revokePlan();planUrlRef.current=url;setPlanUrl(url)};
  const setStandard=(url:string)=>{revokeStandard();standardUrlRef.current=url;setStandardUrl(url)};

  const load=async(preferProtocolId?:string,preferPatrolId?:string,preferCheckpointId?:string)=>{
    setLoading(true);setError('');
    try{
      const rows=await api.patrolProtocols(point.pointId) as Protocol[];setProtocols(rows);
      const postId=selectedPostId||point.posts[0]?.postId||'';if(!selectedPostId&&postId)setSelectedPostId(postId);
      const candidates=rows.filter(p=>p.postId===postId);
      const protocol=(preferProtocolId?rows.find(p=>p.id===preferProtocolId):rows.find(p=>p.id===selectedProtocolId))??candidates[0]??rows[0]??null;
      const patrol=(preferPatrolId?protocol?.patrols.find(p=>p.id===preferPatrolId):protocol?.patrols.find(p=>p.id===selectedPatrolId))??protocol?.patrols[0]??null;
      const checkpoint=(preferCheckpointId?patrol?.checkpoints.find(c=>c.id===preferCheckpointId):patrol?.checkpoints.find(c=>c.id===selectedCheckpointId))??patrol?.checkpoints[0]??null;
      setSelectedProtocolId(protocol?.id??'');setProtocolName(protocol?.name??'');setProtocolDescription(protocol?.description??'');
      setSelectedPatrolId(patrol?.id??'');setPatrolDraft(patrol?clonePatrol(patrol):null);setSelectedCheckpointId(checkpoint?.id??'');
      if(checkpoint?.hasStandardImage){try{const blob=await api.patrolStandardImage(checkpoint.id) as Blob;setStandard(URL.createObjectURL(blob))}catch{revokeStandard()}}else revokeStandard();
    }catch(e){setError(errorText(e))}finally{setLoading(false)}
  };
  const loadAts=async()=>{try{const meta=await api.atsCurrent(point.pointId) as AtsMeta|null;setAts(meta);if(meta){const blob=await api.atsPlan(point.pointId) as Blob;setPlan(URL.createObjectURL(blob))}}catch{setAts(null);revokePlan()}};
  useEffect(()=>{void load();void loadAts();return()=>{revokePlan();revokeStandard()}},[point.pointId]);

  const selectedProtocol=protocols.find(p=>p.id===selectedProtocolId)??null;
  const selectedPost=point.posts.find(p=>p.postId===selectedPostId)??null;
  const selectedCheckpoint=patrolDraft?.checkpoints.find(c=>c.id===selectedCheckpointId)??null;
  const isDraft=selectedProtocol?.status==='BORRADOR';
  const selectedProtocols=protocols.filter(p=>p.postId===selectedPostId);
  const visiblePosts=point.posts.filter(p=>!query.trim()||`${p.postCode} ${p.postName}`.toLowerCase().includes(query.trim().toLowerCase()));
  const postCounts=useMemo(()=>{const m=new Map<string,number>();point.posts.forEach(p=>m.set(p.postId,0));protocols.forEach(p=>m.set(p.postId,(m.get(p.postId)??0)+p.patrols.length));return m},[protocols,point.posts]);
  const allPatrols=protocols.flatMap(p=>p.patrols);
  const activePatrols=protocols.filter(p=>p.status==='VIGENTE').flatMap(p=>p.patrols).length;
  const programmed=allPatrols.filter(p=>p.scheduleType==='PROGRAMMED').length;
  const unprogrammed=allPatrols.filter(p=>p.scheduleType==='UNPROGRAMMED').length;

  const choosePost=(postId:string)=>{setSelectedPostId(postId);const p=protocols.find(x=>x.postId===postId)??null;chooseProtocol(p);};
  const chooseProtocol=(protocol:Protocol|null)=>{setSelectedProtocolId(protocol?.id??'');setProtocolName(protocol?.name??'');setProtocolDescription(protocol?.description??'');const p=protocol?.patrols[0]??null;setSelectedPatrolId(p?.id??'');setPatrolDraft(p?clonePatrol(p):null);setSelectedCheckpointId(p?.checkpoints[0]?.id??'');setTab('HITOS');setHistory(null);setPlacementMode(null);revokeStandard();};
  const choosePatrol=(patrol:Patrol)=>{setSelectedPatrolId(patrol.id);setPatrolDraft(clonePatrol(patrol));setSelectedCheckpointId(patrol.checkpoints[0]?.id??'');setTab(patrol.structureType==='CLOSED'?'HITOS':'DEFINICION');setPlacementMode(null);revokeStandard();if(patrol.checkpoints[0]?.hasStandardImage)void loadImage(patrol.checkpoints[0].id)};
  const chooseCheckpoint=(cp:Checkpoint)=>{setSelectedCheckpointId(cp.id);revokeStandard();if(cp.hasStandardImage)void loadImage(cp.id)};
  const loadImage=async(id:string)=>{try{const blob=await api.patrolStandardImage(id) as Blob;setStandard(URL.createObjectURL(blob))}catch{revokeStandard()}};

  const createProtocol=async()=>{if(!selectedPostId)return;try{const created=await api.createPatrolProtocol({postId:selectedPostId,name:'Nuevo protocolo de patrullas'}) as Protocol;await load(created.id);setNotice(`${created.code} creado como borrador v1.`)}catch(e){setError(errorText(e))}};
  const forkProtocol=async()=>{if(!selectedProtocol)return;try{const forked=await api.forkPatrolProtocol(selectedProtocol.id) as Protocol;await load(forked.id,forked.patrols[0]?.id);setNotice(`Se creó ${forked.code} v${forked.versionNo} en borrador. La versión publicada permanece intacta.`)}catch(e){setError(errorText(e))}};
  const saveProtocol=async()=>{if(!selectedProtocol||!isDraft)return;setSaving(true);try{await api.savePatrolProtocol(selectedProtocol.id,{name:protocolName,description:protocolDescription});await load(selectedProtocol.id,selectedPatrolId,selectedCheckpointId);setNotice('Borrador guardado. La versión vigente no cambia hasta publicar.')}catch(e){setError(errorText(e))}finally{setSaving(false)}};
  const publish=async()=>{if(!selectedProtocol||!isDraft)return;setSaving(true);try{await api.savePatrolProtocol(selectedProtocol.id,{name:protocolName,description:protocolDescription});if(patrolDraft)await savePatrolInternal(false);const published=await api.publishPatrolProtocol(selectedProtocol.id) as Protocol;await load(published.id,selectedPatrolId,selectedCheckpointId);setNotice(`${published.code} v${published.versionNo} publicada. La versión anterior quedó histórica e inmutable.`)}catch(e){setError(errorText(e))}finally{setSaving(false)}};
  const showHistory=async()=>{if(!selectedProtocol)return;try{setHistory(await api.patrolProtocolHistory(selectedProtocol.id) as Protocol[])}catch(e){setError(errorText(e))}};

  const createPatrol=async()=>{if(!selectedProtocol||!isDraft)return;try{const created=await api.createPatrol(selectedProtocol.id,{name:'Nueva patrulla',structureType:'CLOSED',scheduleType:'PROGRAMMED'}) as Patrol;await load(selectedProtocol.id,created.id);setTab('DEFINICION');setNotice(`${created.code} creada.`)}catch(e){setError(errorText(e))}};
  const savePatrolInternal=async(reload=true)=>{if(!patrolDraft||!isDraft)return;const body={name:patrolDraft.name,description:patrolDraft.description,structureType:patrolDraft.structureType,scheduleType:patrolDraft.scheduleType,sequenceType:patrolDraft.sequenceType,windowStart:patrolDraft.windowStart,windowEnd:patrolDraft.windowEnd,repetitions:patrolDraft.repetitions};const saved=await api.savePatrol(patrolDraft.id,body) as Patrol;if(reload){await load(selectedProtocolId,saved.id,selectedCheckpointId);setNotice(`${saved.code} guardada en el borrador.`)}};
  const savePatrol=async()=>{setSaving(true);try{await savePatrolInternal(true)}catch(e){setError(errorText(e))}finally{setSaving(false)}};
  const deletePatrol=async()=>{if(!patrolDraft||!isDraft||!window.confirm(`¿Eliminar ${patrolDraft.code} del borrador?`))return;try{await api.deletePatrol(patrolDraft.id);await load(selectedProtocolId);setNotice('Patrulla eliminada del borrador.')}catch(e){setError(errorText(e))}};

  const addAtsCheckpoint=async(x:number,y:number)=>{if(!patrolDraft||!isDraft||!ats)return;try{const created=await api.createPatrolCheckpoint(patrolDraft.id,{name:'Nuevo Hito',description:'',originMode:'ATS',atsPackageId:ats.id,atsX:x,atsY:y,controlType:'INSPECCION_VISUAL',requiresEvidence:true}) as Checkpoint;setPlacementMode(null);await load(selectedProtocolId,patrolDraft.id,created.id);setTab('REGLAS');setNotice(`${created.code} agregado desde el plano ATS.`)}catch(e){setError(errorText(e))}};
  const addFieldCheckpoint=()=>{if(!patrolDraft||!isDraft)return;if(!navigator.geolocation){setError('Este dispositivo no ofrece geolocalización. Use “Agregar hito en plano” o habilite GPS.');return}setNotice('Capturando coordenadas GPS del Hito…');navigator.geolocation.getCurrentPosition(async pos=>{try{const created=await api.createPatrolCheckpoint(patrolDraft.id,{name:'Nuevo Hito de campo',description:'',originMode:'FIELD',latitude:pos.coords.latitude,longitude:pos.coords.longitude,gpsAccuracyM:pos.coords.accuracy,controlType:'INSPECCION_VISUAL',requiresEvidence:true}) as Checkpoint;await load(selectedProtocolId,patrolDraft.id,created.id);setTab('REGLAS');setNotice(`${created.code}: ubicación GPS capturada. Tome ahora la foto estándar.`)}catch(e){setError(errorText(e))}},err=>setError(`No se pudo capturar GPS: ${err.message}`),{enableHighAccuracy:true,timeout:15000,maximumAge:0});};
  const linkSelectedOnPlan=async(x:number,y:number)=>{if(!selectedCheckpoint||!patrolDraft||!ats)return;try{const cp=selectedCheckpoint;const saved=await api.savePatrolCheckpoint(cp.id,{name:cp.name,description:cp.description,originMode:cp.latitude!=null&&cp.longitude!=null?'MIXED':'ATS',atsPackageId:ats.id,atsX:x,atsY:y,latitude:cp.latitude,longitude:cp.longitude,gpsAccuracyM:cp.gpsAccuracyM,controlType:cp.controlType,requiresEvidence:cp.requiresEvidence,standardImageNotes:cp.standardImageNotes}) as Checkpoint;setPlacementMode(null);await load(selectedProtocolId,patrolDraft.id,saved.id);setNotice(`${saved.code} vinculado al plano ATS.`)}catch(e){setError(errorText(e))}};
  const captureGpsForSelected=()=>{if(!selectedCheckpoint||!patrolDraft||!navigator.geolocation)return;setNotice('Capturando GPS actual…');navigator.geolocation.getCurrentPosition(async pos=>{try{const cp=selectedCheckpoint;const saved=await api.savePatrolCheckpoint(cp.id,{name:cp.name,description:cp.description,originMode:cp.atsX!=null&&cp.atsY!=null?'MIXED':'FIELD',atsPackageId:cp.atsPackageId,atsX:cp.atsX,atsY:cp.atsY,latitude:pos.coords.latitude,longitude:pos.coords.longitude,gpsAccuracyM:pos.coords.accuracy,controlType:cp.controlType,requiresEvidence:cp.requiresEvidence,standardImageNotes:cp.standardImageNotes}) as Checkpoint;await load(selectedProtocolId,patrolDraft.id,saved.id);setNotice(`${saved.code}: GPS actualizado desde campo.`)}catch(e){setError(errorText(e))}},err=>setError(`No se pudo capturar GPS: ${err.message}`),{enableHighAccuracy:true,timeout:15000,maximumAge:0});};

  const updateCheckpoint=<K extends keyof Checkpoint>(key:K,value:Checkpoint[K])=>{if(!patrolDraft||!selectedCheckpoint)return;setPatrolDraft({...patrolDraft,checkpoints:patrolDraft.checkpoints.map(c=>c.id===selectedCheckpoint.id?{...c,[key]:value}:c)});};
  const toggleRule=(kind:RuleType,checked:boolean)=>{if(!patrolDraft||!selectedCheckpoint)return;const rules=selectedCheckpoint.rules.some(r=>r.ruleType===kind)?selectedCheckpoint.rules.map(r=>r.ruleType===kind?{...r,required:checked}:r):[...selectedCheckpoint.rules,{id:`local-${kind}`,checkpointId:selectedCheckpoint.id,sortOrder:selectedCheckpoint.rules.length+1,ruleType:kind,required:checked,evidenceRequired:kind==='FOTOGRAFIA'}];updateCheckpoint('rules',rules)};
  const saveCheckpoint=async()=>{if(!selectedCheckpoint||!patrolDraft||!isDraft)return;setSaving(true);try{const cp=selectedCheckpoint;await api.savePatrolCheckpoint(cp.id,{name:cp.name,description:cp.description,originMode:cp.originMode,atsPackageId:cp.atsPackageId,atsX:cp.atsX,atsY:cp.atsY,latitude:cp.latitude,longitude:cp.longitude,gpsAccuracyM:cp.gpsAccuracyM,controlType:cp.controlType,requiresEvidence:cp.requiresEvidence,standardImageNotes:cp.standardImageNotes});await api.savePatrolCheckpointRules(cp.id,{rules:cp.rules.filter(r=>r.required).map(r=>({ruleType:r.ruleType,required:true,evidenceRequired:r.evidenceRequired}))});await load(selectedProtocolId,patrolDraft.id,cp.id);setNotice(`${cp.code} guardado.`)}catch(e){setError(errorText(e))}finally{setSaving(false)}};
  const deleteCheckpoint=async()=>{if(!selectedCheckpoint||!patrolDraft||!isDraft||!window.confirm(`¿Eliminar ${selectedCheckpoint.code}?`))return;try{await api.deletePatrolCheckpoint(selectedCheckpoint.id);await load(selectedProtocolId,patrolDraft.id);setNotice('Hito eliminado del borrador.')}catch(e){setError(errorText(e))}};
  const uploadPhoto=async(file:File)=>{if(!selectedCheckpoint||!patrolDraft||!isDraft)return;if(file.size>5*1024*1024){setError('La foto estándar no puede superar 5 MB.');return}try{const saved=await api.uploadPatrolStandardImage(selectedCheckpoint.id,file) as Checkpoint;await load(selectedProtocolId,patrolDraft.id,saved.id);setNotice('Foto estándar guardada y versionada.')}catch(e){setError(errorText(e))}};
  const removePhoto=async()=>{if(!selectedCheckpoint||!patrolDraft||!isDraft)return;try{await api.deletePatrolStandardImage(selectedCheckpoint.id);await load(selectedProtocolId,patrolDraft.id,selectedCheckpoint.id);setNotice('Foto estándar retirada del borrador.')}catch(e){setError(errorText(e))}};

  const onPlanClick=(event:ReactMouseEvent<HTMLDivElement>)=>{if(!placementMode||!planUrl||!isDraft)return;const r=event.currentTarget.getBoundingClientRect();const x=Math.max(0,Math.min(1,(event.clientX-r.left)/r.width));const y=Math.max(0,Math.min(1,(event.clientY-r.top)/r.height));if(placementMode==='NEW_ATS')void addAtsCheckpoint(x,y);else void linkSelectedOnPlan(x,y)};
  const evidence=patrolDraft?.checkpoints.filter(c=>c.requiresEvidence)??[];

  return <div className="services-v01 patrol-config-page">
    <div className="ser-breadcrumbs"><button onClick={onBack}><ArrowLeft size={15}/>Volver a Configuración</button><span>/</span><small>Patrullas</small></div>
    <div className="pat-titlebar"><div><div className="ser-title-row"><h2>Patrullas</h2><span>Configuración de recorridos, hitos y reglas por Puesto</span></div><small>Patrullas Cerradas/Abiertas × Programadas/No Programadas · configuración mixta en campo y plano ATS.</small></div><div className="pat-version-principle"><ShieldCheck size={16}/><span>Todo cambio publicado genera una nueva versión inmutable.</span></div></div>
    <div className="bit-context panel"><div><span>Compañía</span><strong>{point.companyName}</strong></div><div><span>Servicio</span><strong>{point.serviceName}</strong></div><div><span>Cliente</span><strong>{point.clientName}</strong></div><div><span>Punto</span><strong>{point.pointName}</strong></div><div><span>Plano ATS</span><strong>{ats?`r${ats.revisionNo} · vigente`:'No disponible'}</strong></div></div>
    <div className="ser-kpis pat-kpis"><article><span className="ser-kpi-icon blue"><ShieldCheck/></span><div><small>Puestos</small><strong>{point.posts.length}</strong><em>en el punto</em></div></article><article><span className="ser-kpi-icon blue"><Route/></span><div><small>Patrullas</small><strong>{allPatrols.length}</strong><em>configuradas</em></div></article><article><span className="ser-kpi-icon green"><BadgeCheck/></span><div><small>Patrullas activas</small><strong>{activePatrols}</strong><em>en protocolos vigentes</em></div></article><article><span className="ser-kpi-icon green"><Clock/></span><div><small>Programadas</small><strong>{programmed}</strong><em>con ventana</em></div></article><article><span className="ser-kpi-icon amber"><RefreshCcw/></span><div><small>No programadas</small><strong>{unprogrammed}</strong><em>inicio según necesidad</em></div></article></div>
    {error&&<div className="ser-error"><AlertTriangle size={16}/><span>{error}</span><button onClick={()=>setError('')}>Cerrar</button></div>}
    {notice&&<div className="posts-notice"><Info size={15}/><span>{notice}</span><button className="icon-only" onClick={()=>setNotice('')}><X size={14}/></button></div>}

    <div className="pat-layout">
      <section className="ser-table-card pat-posts"><header><div><h3>Puestos del Punto</h3><span>Seleccione un Puesto</span></div></header><div className="bit-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar puesto…"/></div><div className="bit-post-list">{visiblePosts.map(post=><button key={post.postId} className={selectedPostId===post.postId?'selected':''} onClick={()=>choosePost(post.postId)}><span className="bit-post-icon"><ShieldCheck size={17}/></span><div><strong>{post.postCode}</strong><span>{post.postName}</span><small>{postCounts.get(post.postId)??0} patrulla{(postCounts.get(post.postId)??0)===1?'':'s'}</small></div><ChevronRight size={15}/></button>)}</div><div className="pat-matrix"><h4>Matriz de modalidades</h4><div><span><b>Cerrada</b> + Programada</span><span><b>Cerrada</b> + No programada</span><span><b>Abierta</b> + Programada</span><span><b>Abierta</b> + No programada</span></div></div></section>

      <section className="pat-middle">
        <div className="ser-table-card pat-protocols"><header><div><h3>Protocolos del Puesto</h3><span>{selectedPost?`${selectedPost.postCode} · ${selectedPost.postName}`:'Seleccione un Puesto'}</span></div><button className="primary compact" onClick={()=>void createProtocol()} disabled={!selectedPostId}><Plus size={14}/>Crear protocolo</button></header><table><thead><tr><th>Código</th><th>Nombre</th><th>Estado</th><th>Versión</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Cargando…</td></tr>:selectedProtocols.map(p=><tr key={p.id} className={p.id===selectedProtocolId?'selected':''} onClick={()=>chooseProtocol(p)}><td>{p.code}</td><td><strong>{p.name}</strong></td><td><span className={`pat-state ${p.status.toLowerCase()}`}>{statusLabel(p.status)}</span></td><td>v{p.versionNo}</td></tr>)}</tbody></table></div>
        <div className="ser-table-card pat-list"><header><div><h3>Patrullas del protocolo</h3><span>{selectedProtocol?`${selectedProtocol.code} · v${selectedProtocol.versionNo}`:'Seleccione un protocolo'}</span></div><button className="primary compact" onClick={()=>void createPatrol()} disabled={!isDraft}><Plus size={14}/>Crear patrulla</button></header><table><thead><tr><th>Código</th><th>Patrulla</th><th>Espacial</th><th>Temporal</th></tr></thead><tbody>{selectedProtocol?.patrols.length?selectedProtocol.patrols.map(p=><tr key={p.id} className={p.id===selectedPatrolId?'selected':''} onClick={()=>choosePatrol(p)}><td>{p.code}</td><td><strong>{p.name}</strong><small>v{p.versionNo}</small></td><td><span className={`pat-chip ${p.structureType.toLowerCase()}`}>{structureLabel(p.structureType)}</span></td><td><span className={`pat-chip ${p.scheduleType.toLowerCase()}`}>{scheduleLabel(p.scheduleType)}</span></td></tr>):<tr><td colSpan={4} className="bit-empty-cell">Este protocolo no tiene patrullas.</td></tr>}</tbody></table></div>
      </section>

      <section className="ser-table-card pat-editor">
        {!selectedProtocol?<div className="bit-detail-empty"><Route size={30}/><strong>Seleccione o cree un protocolo</strong><span>Después podrá crear Patrullas y sus reglas.</span></div>:<>
          <div className="pat-protocol-toolbar"><div><span>Protocolo de patrullas</span><strong>{selectedPost?`${selectedPost.postCode} · ${selectedPost.postName}`:'Puesto no seleccionado'}</strong></div><div className="pat-head-actions"><button onClick={()=>void showHistory()}><History size={15}/>Historial</button>{isDraft?<><button onClick={()=>void saveProtocol()} disabled={saving}><Save size={15}/>Guardar borrador</button><button className="primary" onClick={()=>void publish()} disabled={saving}><ShieldCheck size={15}/>Publicar versión</button></>:<button className="primary" onClick={()=>void createProtocol()} disabled={!selectedPostId}><Plus size={15}/>Crear nuevo protocolo</button>}</div></div>
          <div className="pat-protocol-identity"><div className="pat-head-line"><strong>{selectedProtocol.code}</strong><span className={`pat-state ${selectedProtocol.status.toLowerCase()}`}>{statusLabel(selectedProtocol.status)}</span><span className="pat-version-pill">Versión {selectedProtocol.versionNo}</span></div>{isDraft?<input value={protocolName} onChange={e=>setProtocolName(e.target.value)} className="pat-protocol-name"/>:<h2>{selectedProtocol.name}</h2>}<div className="pat-head-summary"><span><b>Estado:</b> {statusLabel(selectedProtocol.status)}</span><span><b>Patrullas:</b> {selectedProtocol.patrols.length}</span><span><b>Última publicación:</b> {selectedProtocol.lastPublishedAt?new Date(selectedProtocol.lastPublishedAt).toLocaleString('es-EC'):'—'}</span></div></div>
          {isDraft?<div className="pat-version-banner draft"><Info size={16}/><div><strong>Borrador editable</strong><span>Los cambios se guardan únicamente en esta versión. La configuración vigente no cambia hasta publicar.</span></div></div>:<div className="pat-version-banner"><ShieldCheck size={16}/><div><strong>Versión publicada · solo lectura</strong><span>Esta versión es inmutable. Si necesita una variante adicional, cree un nuevo protocolo y publíquelo cuando esté listo.</span></div></div>}
          {patrolDraft?<>
            <div className="pat-patrol-header"><div><span className="pat-patrol-eyebrow">Patrulla seleccionada</span><strong>{patrolDraft.code} · {patrolDraft.name}</strong><div className="pat-patrol-meta"><span>v{patrolDraft.versionNo}</span><span className={`pat-chip ${patrolDraft.structureType.toLowerCase()}`}>{structureLabel(patrolDraft.structureType)}</span><span className={`pat-chip ${patrolDraft.scheduleType.toLowerCase()}`}>{scheduleLabel(patrolDraft.scheduleType)}</span></div></div>{isDraft&&<div className="pat-patrol-actions"><button onClick={()=>void savePatrol()}><Save size={15}/>Guardar patrulla</button><button className="danger-ghost" onClick={()=>void deletePatrol()}><Trash2 size={15}/>Eliminar</button></div>}</div>
            <div className="bit-step-tabs pat-tabs">{([['DEFINICION','A. Definición'],['PROGRAMACION','B. Programación'],['HITOS','C. Hitos'],['REGLAS','D. Reglas por hito'],['EVIDENCIAS','E. Evidencias'],['VERSIONADO','F. Versionado']] as [Tab,string][]).map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>
            <fieldset className="pat-fieldset" disabled={!isDraft}>
              {tab==='DEFINICION'&&<div className="pat-section"><div className="pat-form-grid"><label><span>Nombre</span><input value={patrolDraft.name} onChange={e=>setPatrolDraft({...patrolDraft,name:e.target.value})}/></label><label className="wide"><span>Descripción</span><textarea value={patrolDraft.description} onChange={e=>setPatrolDraft({...patrolDraft,description:e.target.value})}/></label></div><div className="pat-choice-row"><div><span>Modalidad espacial</span><div><button type="button" className={patrolDraft.structureType==='CLOSED'?'active':''} onClick={()=>setPatrolDraft({...patrolDraft,structureType:'CLOSED',sequenceType:patrolDraft.sequenceType??'STRICT'})}>Cerrada</button><button type="button" className={patrolDraft.structureType==='OPEN'?'active':''} onClick={()=>{if(patrolDraft.checkpoints.length&&!window.confirm('Cambiar a Abierta eliminará los Hitos predefinidos al guardar. ¿Continuar?'))return;setPatrolDraft({...patrolDraft,structureType:'OPEN',sequenceType:null})}}>Abierta</button></div></div><div><span>Modalidad temporal</span><div><button type="button" className={patrolDraft.scheduleType==='PROGRAMMED'?'active':''} onClick={()=>setPatrolDraft({...patrolDraft,scheduleType:'PROGRAMMED',windowStart:patrolDraft.windowStart??'22:00',windowEnd:patrolDraft.windowEnd??'22:45'})}>Programada</button><button type="button" className={patrolDraft.scheduleType==='UNPROGRAMMED'?'active':''} onClick={()=>setPatrolDraft({...patrolDraft,scheduleType:'UNPROGRAMMED',windowStart:null,windowEnd:null})}>No programada</button></div></div></div></div>}
              {tab==='PROGRAMACION'&&<div className="pat-section">{patrolDraft.scheduleType==='PROGRAMMED'?<><div className="pat-section-heading"><Clock/><div><strong>Ventana de ejecución</strong><span>Máximo 1 hora. La patrulla debe finalizar dentro de la ventana para ser puntual.</span></div></div><div className="pat-time-row"><label><span>Desde</span><input type="time" value={patrolDraft.windowStart??''} onChange={e=>setPatrolDraft({...patrolDraft,windowStart:e.target.value})}/></label><label><span>Hasta</span><input type="time" value={patrolDraft.windowEnd??''} onChange={e=>setPatrolDraft({...patrolDraft,windowEnd:e.target.value})}/></label></div></>:<><div className="pat-section-heading"><RefreshCcw/><div><strong>No Programada</strong><span>Puede iniciarse según necesidad operacional; las ejecuciones se miden separadamente.</span></div></div><label className="pat-small-input"><span>Ejecuciones requeridas</span><input type="number" min={1} value={patrolDraft.repetitions} onChange={e=>setPatrolDraft({...patrolDraft,repetitions:Math.max(1,Number(e.target.value)||1)})}/></label></>}{patrolDraft.structureType==='CLOSED'&&<div className="pat-sequence"><span>Secuencia de Hitos</span><button type="button" className={patrolDraft.sequenceType==='STRICT'?'active':''} onClick={()=>setPatrolDraft({...patrolDraft,sequenceType:'STRICT'})}>Estricta</button><button type="button" className={patrolDraft.sequenceType==='FLEXIBLE'?'active':''} onClick={()=>setPatrolDraft({...patrolDraft,sequenceType:'FLEXIBLE'})}>Flexible</button></div>}</div>}
              {tab==='HITOS'&&<div className="pat-section">{patrolDraft.structureType==='OPEN'?<div className="pat-open-card"><Route/><strong>Patrulla Abierta</strong><span>No tiene Hitos predefinidos. El Agente crea y cierra Hitos durante cada ejecución concreta.</span></div>:<><div className="pat-hit-toolbar"><div><strong>Hitos del recorrido ({patrolDraft.checkpoints.length}/25)</strong><span>Puede mezclar Hitos levantados en campo con Hitos definidos sobre ATS.</span></div><div><button type="button" onClick={()=>setPlacementMode('NEW_ATS')} disabled={!ats}><MapIcon size={14}/>+ Agregar hito en plano</button><button type="button" className="primary" onClick={addFieldCheckpoint}><Smartphone size={14}/>+ Agregar hito en campo</button></div></div><div className="pat-map-grid"><div className="pat-hit-list">{patrolDraft.checkpoints.map(cp=><button type="button" key={cp.id} className={cp.id===selectedCheckpointId?'selected':''} onClick={()=>chooseCheckpoint(cp)}><MapPin size={15}/><div><b>{cp.code}</b><span>{cp.name}</span></div><em className={cp.originMode.toLowerCase()}>{cp.originMode==='ATS'?'Plano ATS':cp.originMode==='FIELD'?'Campo':'Mixto'}</em></button>)}</div><div className={`pat-map ${placementMode?'placing':''}`} onClick={onPlanClick}>{planUrl?<><img src={planUrl} alt="Plano ATS"/>{patrolDraft.checkpoints.filter(cp=>cp.atsX!=null&&cp.atsY!=null).map(cp=><button type="button" key={cp.id} className={`pat-marker ${cp.originMode.toLowerCase()} ${cp.id===selectedCheckpointId?'selected':''}`} style={{left:`${(cp.atsX??0)*100}%`,top:`${(cp.atsY??0)*100}%`}} onClick={e=>{e.stopPropagation();chooseCheckpoint(cp)}}>{cp.code}</button>)}{placementMode&&<div className="pat-placement-note">{placementMode==='NEW_ATS'?'Haga clic en el plano para ubicar el nuevo Hito':'Haga clic para vincular el Hito seleccionado al plano'}</div>}</>:<div className="pat-no-map"><MapIcon/><strong>Importe un `.ats` para configurar Hitos desde el plano</strong></div>}</div></div><div className="pat-info"><Info size={14}/><span>Modo mixto: cada Hito conserva si nació en Plano ATS, Campo o fue enriquecido por ambos métodos.</span></div></>}</div>}
              {tab==='REGLAS'&&<div className="pat-section">{!selectedCheckpoint?<div className="pat-open-card"><MapPin/><strong>Seleccione un Hito</strong><span>Las reglas se configuran Hito por Hito.</span></div>:<CheckpointEditor cp={selectedCheckpoint} isDraft={isDraft} standardUrl={standardUrl} update={updateCheckpoint} toggleRule={toggleRule} onSave={()=>void saveCheckpoint()} onDelete={()=>void deleteCheckpoint()} onCaptureGps={captureGpsForSelected} onLinkPlan={()=>setPlacementMode('LINK_SELECTED')} onPhoto={()=>photoInput.current?.click()} onRemovePhoto={()=>void removePhoto()}/>}</div>}
              {tab==='EVIDENCIAS'&&<div className="pat-section"><div className="pat-section-heading"><FileImage/><div><strong>Evidencias</strong><span>Resumen derivado de las reglas de los Hitos; no se configura nuevamente aquí.</span></div></div><div className="pat-evidence-list">{evidence.map(cp=><button type="button" key={cp.id} onClick={()=>{chooseCheckpoint(cp);setTab('REGLAS')}}><span><Camera size={16}/></span><div><strong>{cp.code} · {cp.name}</strong><small>{cp.hasStandardImage?`Foto estándar v${cp.standardImageVersion}`:'Sin foto estándar'}</small></div><em className={cp.hasStandardImage?'ready':'pending'}>{cp.hasStandardImage?'Preparado':'Pendiente'}</em></button>)}{!evidence.length&&<p>No existen Hitos con evidencia requerida.</p>}</div></div>}
              {tab==='VERSIONADO'&&<div className="pat-section"><div className="pat-version-card"><History/><div><strong>Patrón de versionado obligatorio</strong><p>Guardar modifica únicamente el borrador. Publicar crea una versión inmutable del Protocolo con todas sus Patrullas, Hitos, Reglas, ubicaciones y Fotos estándar. Para editar una versión publicada, SGI crea un nuevo borrador por copia.</p><button type="button" onClick={()=>void showHistory()}>Ver historial de versiones</button></div></div></div>}
            </fieldset>
          </>:<div className="bit-detail-empty"><Route size={28}/><strong>Cree o seleccione una Patrulla</strong><span>El Protocolo puede contener varias Patrullas preparadas.</span></div>}
        </>}
      </section>
    </div>

    <input ref={photoInput} type="file" accept="image/png,image/jpeg,image/webp" capture="environment" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void uploadPhoto(f);e.currentTarget.value=''}}/>
    {history&&<div className="pat-modal-backdrop" onClick={()=>setHistory(null)}><section className="pat-history-modal" onClick={e=>e.stopPropagation()}><header><div><h3>Historial · {selectedProtocol?.code}</h3><span>Las versiones publicadas son snapshots inmutables.</span></div><button onClick={()=>setHistory(null)}><X size={18}/></button></header><div>{history.map(v=><article key={v.id}><div><strong>v{v.versionNo}</strong><span className={`pat-state ${v.status.toLowerCase()}`}>{statusLabel(v.status)}</span></div><div><b>{v.name}</b><small>{v.patrols.length} patrullas · {v.patrols.reduce((s,p)=>s+p.checkpoints.length,0)} hitos</small></div><small>{v.lastPublishedAt?new Date(v.lastPublishedAt).toLocaleString('es-EC'):'Borrador no publicado'}</small></article>)}</div></section></div>}
  </div>;
}

function CheckpointEditor({cp,isDraft,standardUrl,update,toggleRule,onSave,onDelete,onCaptureGps,onLinkPlan,onPhoto,onRemovePhoto}:{cp:Checkpoint;isDraft:boolean;standardUrl:string;update:<K extends keyof Checkpoint>(k:K,v:Checkpoint[K])=>void;toggleRule:(k:RuleType,v:boolean)=>void;onSave:()=>void;onDelete:()=>void;onCaptureGps:()=>void;onLinkPlan:()=>void;onPhoto:()=>void;onRemovePhoto:()=>void}){
  return <div className="pat-checkpoint-editor"><div className="pat-checkpoint-head"><div><strong>{cp.code} · {cp.name}</strong><span>Origen: {cp.originMode==='ATS'?'Plano ATS':cp.originMode==='FIELD'?'Campo':'Mixto'}</span></div>{isDraft&&<div><button type="button" onClick={onSave}><Save size={14}/>Guardar Hito</button><button type="button" className="danger-ghost" onClick={onDelete}><Trash2 size={14}/></button></div>}</div><div className="pat-checkpoint-grid"><section><label><span>Nombre del Hito</span><input value={cp.name} onChange={e=>update('name',e.target.value)}/></label><label><span>Descripción</span><textarea value={cp.description} onChange={e=>update('description',e.target.value)}/></label><label><span>Tipo de control</span><select value={cp.controlType} onChange={e=>update('controlType',e.target.value as RuleType)}>{Object.entries(RULE_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="pat-check"><input type="checkbox" checked={cp.requiresEvidence} onChange={e=>update('requiresEvidence',e.target.checked)}/><span>Requiere evidencia</span></label><div className="pat-location-actions"><button type="button" onClick={onLinkPlan}><MapIcon size={14}/>{cp.atsX!=null?'Reubicar en plano':'Vincular en plano ATS'}</button><button type="button" onClick={onCaptureGps}><Navigation size={14}/>{cp.latitude!=null?'Actualizar GPS':'Capturar GPS en campo'}</button></div><div className="pat-coordinates"><span>ATS: {cp.atsX!=null?`${(cp.atsX*100).toFixed(1)}%, ${((cp.atsY ?? 0)*100).toFixed(1)}%`:'—'}</span><span>GPS: {cp.latitude!=null?`${cp.latitude.toFixed(6)}, ${cp.longitude?.toFixed(6)}`:'—'}</span></div></section><section><strong>Reglas del Hito</strong><div className="pat-rule-list">{(Object.keys(RULE_LABEL) as RuleType[]).map(kind=>{const r=cp.rules.find(x=>x.ruleType===kind);return <label key={kind}><input type="checkbox" checked={!!r?.required} onChange={e=>toggleRule(kind,e.target.checked)}/><span>{RULE_LABEL[kind]}</span></label>})}</div><div className="pat-standard"><div className="pat-standard-title"><strong>Foto estándar</strong><span>Patrón para futura auditoría VISINT</span></div>{standardUrl?<div className="pat-photo-preview"><img src={standardUrl} alt="Foto estándar"/><div><span>v{cp.standardImageVersion}</span><button type="button" onClick={onPhoto}><Upload size={13}/>Reemplazar</button><button type="button" onClick={onRemovePhoto}><Trash2 size={13}/></button></div></div>:<button type="button" className="pat-photo-empty" onClick={onPhoto}><Camera size={22}/><strong>Tomar / cargar foto estándar</strong><span>En móvil abre la cámara; en oficina permite cargar archivo.</span></button>}<label><span>Notas del estándar</span><textarea value={cp.standardImageNotes??''} onChange={e=>update('standardImageNotes',e.target.value)} placeholder="Ej. equipo completo visible, panel frontal legible, sin obstrucciones…"/></label></div></section></div></div>;
}
